Decouple internal session class from session (#638)
* fix NoClassDefFoundError in openam-clientsdk, decouple from InternalSession

* remove unused import and add copyright

* fix i18n artifacts for client sdk