Fix for OPENAM-4318 - reviewed by Jonathan over IM InstallTools now contains forgerock-util to prevent NoClassDefFoundErrors due to unsatisfied Guice dependencies.